[project]
name = "module_euro_industry"
authors = ["See AUTHORS file"]
description = "A module to create disaggregated energy demand of European industries at any resolution."
license = "Apache-2.0"
readme = "README.md"
channels = ["conda-forge", "bioconda"]
platforms = ["win-64", "linux-64", "osx-arm64"]
homepage = "https://clio.readthedocs.io/"

[dependencies]
clio-tools = ">=2025.03.03"
conda = ">=25.0.0"
ipdb = ">=0.13.13"
ipykernel = ">=6.29.5"
jsonschema = ">=4.0.0"
mypy = ">=1.15.0"
pytest = ">=8.3.5"
python = ">=3.12"
ruff = ">=0.9.9"
snakefmt = ">=0.10.2"
snakemake-minimal = ">=8.29.0"
numpy = ">=2.3.4,<3"
pandas = ">=2.3.3,<3"
country_converter = ">=1.3.2,<2"
tqdm = ">=4.67.1,<5"
pyxlsb = ">=1.0.10,<2"
geopandas = ">=1.1.1,<2"
geopy = ">=2.4.1,<3"

[tasks]
test-integration = {cmd = "pytest tests/clio_test.py"}
